sudo: false
cache:
  directories:
    - $HOME/.m2
language: java
jdk:
  - oraclejdk8
services:
  - redis-server
install: true
script:
  - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || ./mvnw package -DskipITs -Pfull -U -Dmaven.test.redirectTestOutputToFile=false'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] || ./mvnw package -DskipTests -U -Dmaven.test.redirectTestOutputToFile=false'

