spring:
  main:
    show_banner: false
  cloud:
    deployer:
      yarn:
        version: "@project.version@"
  yarn:
    appType: DATAFLOW
    applicationBaseDir: ${spring.cloud.deployer.yarn.app.baseDir:/dataflow}/apps/task/
    client:
      enabled: true
      clientClass: org.springframework.cloud.deployer.spi.yarn.DeployerApplicationYarnClient
      files:
        - "file:${deployer.yarn.app.appmaster.path:lib}/spring-cloud-deployer-yarn-tasklauncherappmaster-*.jar"
        - "file:${deployer.yarn.app.config.path:config}/servers.yml*"
      queue: ${spring.cloud.deployer.yarn.app.taskappmaster.queue:default}
      labelExpression: ${spring.cloud.deployer.yarn.app.taskappmaster.labelExpression:}
      launchcontext:
        options:
          - ${spring.cloud.deployer.yarn.app.taskappmaster.javaOpts:}
        arguments:
          -Dspring.config.location: servers.yml
        archiveFile: spring-cloud-deployer-yarn-tasklauncherappmaster-${spring.cloud.deployer.yarn.version}.jar
      localizer:
        patterns:
          - "spring-cloud-deployer-yarn-tasklauncherappmaster-*.jar"
          - "servers.yml"
      resource:
        memory: ${spring.cloud.deployer.yarn.app.taskappmaster.memory:512m}
        virtualCores: ${spring.cloud.deployer.yarn.app.taskappmaster.virtualCores:1}
    container:
      enabled: false
